/**********************************************************************************************************************
 * \file App_Debug.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "App_Debug.h"

#include "Ifx_Types.h"
#include "IfxAsclin_Asc.h"
#include "IfxAsclin_PinMap.h"
#include "IfxCpu_Irq.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"

#include <stdio.h>
#include <stdarg.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define DEBUG_UART_BAUDRATE       115200u
#define ASC_TX_BUFFER_SIZE        512u
#define ASC_RX_BUFFER_SIZE        64u
#define ASCLIN_TX_FIFO_SIZE       16u

#define ISR_PRIORITY_ASCLIN0_TX   10u
#define ISR_PRIORITY_ASCLIN0_RX   11u
#define ISR_PRIORITY_ASCLIN0_ER   12u
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static IfxAsclin_Asc g_debugAsc;

static uint8 g_ascTxBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_ascRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
/*********************************************************************************************************************/

static QueueHandle_t g_debugLogQueue = NULL;
static bool g_debugUartInitialized = false;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static void DebugUart_putcPolling(uint8 ch);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
IFX_INTERRUPT(asclin0TxISR, 0, ISR_PRIORITY_ASCLIN0_TX);
void asclin0TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_debugAsc);
}

IFX_INTERRUPT(asclin0RxISR, 0, ISR_PRIORITY_ASCLIN0_RX);
void asclin0RxISR(void)
{
    IfxAsclin_Asc_isrReceive(&g_debugAsc);
}

IFX_INTERRUPT(asclin0ErrISR, 0, ISR_PRIORITY_ASCLIN0_ER);
void asclin0ErrISR(void)
{
    IfxAsclin_Asc_isrError(&g_debugAsc);
}

void DebugUart_init(void)
{
    if (g_debugUartInitialized)
    {
        return;
    }

    IfxAsclin_Asc_Config ascConfig;

    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN0);

    ascConfig.baudrate.baudrate = DEBUG_UART_BAUDRATE;

    /*
     * Use polling for debug output so boot logs do not depend on ASCLIN
     * interrupt delivery while we are bringing up the board.
     */
    ascConfig.interrupt.txPriority = 0u;
    ascConfig.interrupt.rxPriority = 0u;
    ascConfig.interrupt.erPriority = 0u;
    ascConfig.interrupt.typeOfService = IfxSrc_Tos_cpu0;

    ascConfig.txBuffer = g_ascTxBuffer;
    ascConfig.txBufferSize = ASC_TX_BUFFER_SIZE;

    ascConfig.rxBuffer = g_ascRxBuffer;
    ascConfig.rxBufferSize = ASC_RX_BUFFER_SIZE;

    /*
     * TC375 Lite Kit V2 USB serial:
     * TX = P14.0 / ASCLIN0.ATX0
     * RX = P14.1 / ASCLIN0.ARX0
     */
    const IfxAsclin_Asc_Pins pins = {
        NULL_PTR,                    IfxPort_InputMode_pullUp,
        &IfxAsclin0_RXA_P14_1_IN,    IfxPort_InputMode_pullUp,
        NULL_PTR,                    IfxPort_OutputMode_pushPull,
        &IfxAsclin0_TX_P14_0_OUT,    IfxPort_OutputMode_pushPull,
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };

    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_debugAsc, &ascConfig);

    g_debugUartInitialized = true;
}

static void DebugUart_putcPolling(uint8 ch)
{
    while (IfxAsclin_getTxFifoFillLevel(&MODULE_ASCLIN0) >= ASCLIN_TX_FIFO_SIZE)
    {
    }

    (void)IfxAsclin_write8(&MODULE_ASCLIN0, &ch, 1U);
}

void DebugUart_puts(const char *str)
{
    if ((str == NULL) || (!g_debugUartInitialized))
    {
        return;
    }

    while (*str != '\0')
    {
        DebugUart_putcPolling((uint8)*str);
        str++;
    }
}

void DebugUart_printf(const char *fmt, ...)
{
    char buffer[DEBUG_LOG_MESSAGE_SIZE];

    va_list args;
    va_start(args, fmt);
    vsnprintf(buffer, sizeof(buffer), fmt, args);
    va_end(args);

    DebugUart_puts(buffer);
}

void DebugApp_init(void)
{
    DebugUart_init();

    if (g_debugLogQueue == NULL)
    {
        g_debugLogQueue = xQueueCreate(DEBUG_LOG_QUEUE_LENGTH, sizeof(DebugLogMessage_t));
    }

    DebugUart_printf("[DBG] UART logger init\r\n");
}

bool DebugLog_isReady(void)
{
    return (g_debugUartInitialized && (g_debugLogQueue != NULL));
}

void DebugLog_printf(const char *fmt, ...)
{
    DebugLogMessage_t msg;

    if (fmt == NULL)
    {
        return;
    }

    va_list args;
    va_start(args, fmt);
    vsnprintf(msg.text, sizeof(msg.text), fmt, args);
    va_end(args);

    /*
     * Before scheduler starts, direct output is safe and useful for boot logs.
     * After scheduler starts, send to the debug task queue.
     */
    if ((g_debugLogQueue == NULL) || (xTaskGetSchedulerState() == taskSCHEDULER_NOT_STARTED))
    {
        DebugUart_puts(msg.text);
        return;
    }

    /*
     * Do not block producer tasks on logging. If the queue is full, drop the log.
     * Increase DEBUG_LOG_QUEUE_LENGTH if logs are missing.
     */
    (void)xQueueSend(g_debugLogQueue, &msg, 0u);
}

void task_app_debug(void *arg)
{
    (void)arg;

    DebugLogMessage_t msg;

    if (!g_debugUartInitialized)
    {
        DebugUart_init();
    }

    for (;;)
    {
        if ((g_debugLogQueue != NULL) &&
            (xQueueReceive(g_debugLogQueue, &msg, portMAX_DELAY) == pdTRUE))
        {
            DebugUart_puts(msg.text);
        }
    }
}
/*********************************************************************************************************************/
