/**********************************************************************************************************************
 * \file APP_Debug.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef APP_DEBUG_H_
#define APP_DEBUG_H_

/*
 * FreeRTOS UART logger.
 *
 * - DebugApp_init() initializes ASCLIN0 UART and the log queue.
 * - task_app_debug() flushes queued log messages to UART.
 * - DebugLog_printf() is the API other tasks should use.
 *
 * Do not print directly from every task using blocking UART writes.
 * Queue logs here and let task_app_debug own the UART.
 */

 /*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define TASK_PRIO_DEBUG     (3u)
#define TASK_STACK_DEBUG    (configMINIMAL_STACK_SIZE)

#define DEBUG_LOG_QUEUE_LENGTH    16u
#define DEBUG_LOG_MESSAGE_SIZE    256u
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
typedef struct
{
    char text[DEBUG_LOG_MESSAGE_SIZE];
} DebugLogMessage_t;
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
void DebugApp_init(void);
void task_app_debug(void *arg);

void DebugLog_printf(const char *fmt, ...);

/* Low-level direct UART output. Use only before scheduler or inside debug task. */
void DebugUart_init(void);
void DebugUart_puts(const char *str);
void DebugUart_printf(const char *fmt, ...);

bool DebugLog_isReady(void);
/*********************************************************************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* APP_DEBUG_H_ */
